In [ ]:
#Assignment-1 by Partha Aakash Cheepurupalli

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

In [3]:
#Import NumPy as np
import numpy as np

In [4]:
#Create an array of 10 zeros
z1=np.zeros(10)
z1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Create an array of 10 ones
z=np.ones(10)
z


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#Create an array of 10 fives
z3=np.full(10,5.0)
z3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#Create an array of the integers from 10 to 50
a=np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
#Create an array of all the even integers from 10 to 50
ev_arr=np.arange(10,51,2)
ev_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
#Create a 3x3 matrix with values ranging from 0 to 8
a1=np.array([[0,1,2,],[3,4,5],[6,7,8]])
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#Create a 3x3 identity matrix
a2=np.eye(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#Use NumPy to generate a random number between 0 and 1
ran_num=np.random.rand()
ran_num

0.020344854871913065

In [14]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
a=np.random.randn(25)
a

array([-0.77661201,  1.01284811,  2.07320309, -0.92007209,  0.97565968,
       -1.02204019, -0.47054259,  1.45591397, -1.39482129, -2.13165192,
        0.04409449, -0.57489744, -1.19771534,  0.85672911, -0.54451511,
        0.63832051, -0.07089592,  1.27496467,  1.21096697, -0.50531318,
        0.9164087 ,  0.8378616 ,  0.1286658 ,  1.64449578, -0.04900585])

In [15]:
#Create the following matrix:
ar=np.arange(0.01,1.0,0.01)
ar

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [16]:
#Create an array of 20 linearly spaced points between 0 and 1:
la=np.linspace(0,1,20)
la

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing & Selection

In [17]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


In [18]:
mat[2:6,1:6]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
mat[3:4,4:6]

array([[20]])

In [20]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [21]:
mat[4:6,0:6]

array([[21, 22, 23, 24, 25]])

In [22]:
mat[4:6,0:6]

array([[21, 22, 23, 24, 25]])

Get the Sum of all the values in mat

In [24]:
sum1=np.sum(mat)
sum1

325

Get the standard deviation of the values in mat

In [26]:
sd=np.std(mat)
sd

7.211102550927978

Get the sum of all the columns in mat

In [28]:
col_sum=np.sum(mat,axis=0)
col_sum

array([55, 60, 65, 70, 75])